name: Pipeline-step-7

on:
  push:
    branches:
      - main  # Adjust the branch as needed

env:
  APPLICATION_NAME: flaskapp
  REGISTRY: ghcr.io
  IMAGE_NAME: adiouma-dione/devops-labs-flask-app

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 test_app.py
      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}  # Use GitHub token as the password

